pipeline {
    agent any

    environment {
        TF_CLI_ARGS = "-no-color -auto-approve"
    }

    parameters {
        booleanParam(name: "DESTROY", defaultValue: false)
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    dir('infra/app') {
                        sh 'make init'
                    }
                }
            }
        }

        stage('Validate') {
            steps {
                script {
                    dir('infra/app') {
                        sh 'make validate'
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    dir('infra/app') {
                        sh 'make plan'
                    }
                }
            }
        }

        stage('Apply') {
            when {
                environment name: "DESTROY", value: "false"
            }

            steps {
                input 'Start?'
                script {
                    dir('infra/app') {
                        sh 'make apply'
                    }
                }
            }
        }

        stage('Destroy') {
            when {
                environment name: "DESTROY", value: "true"
            }

            steps {
                input 'Start?'
                script {
                    dir('infra/app') {
                        sh 'make destroy'
                    }
                }
            }
        }
    }
}
