pipeline {
    agent any

    environment {
        TF_CLI_ARGS = "-no-color"
        TF_CLI_ARGS_apply = "-auto-approve"
        TF_CLI_ARGS_destroy = "-auto-approve"
    }

    parameters {
        booleanParam(name: "DESTROY", defaultValue: false)
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    dir('infra/app') {
                        withCredentials([
                            string(credentialsId: 'TF_VAR_admin_password', variable: 'TF_VAR_admin_password'),
                            string(credentialsId: 'TF_VAR_subscription_id', variable: 'TF_VAR_subscription_id'),
                            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
                            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID') ]) {
                                sh 'make init'
                        }
                    }
                }
            }
        }

        stage('Validate') {
            steps {
                script {
                    dir('infra/app') {
                        withCredentials([
                            string(credentialsId: 'TF_VAR_admin_password', variable: 'TF_VAR_admin_password'),
                            string(credentialsId: 'TF_VAR_subscription_id', variable: 'TF_VAR_subscription_id'),
                            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
                            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID') ]) {
                                sh 'make validate'
                        }
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    dir('infra/app') {
                        withCredentials([
                            string(credentialsId: 'TF_VAR_admin_password', variable: 'TF_VAR_admin_password'),
                            string(credentialsId: 'TF_VAR_subscription_id', variable: 'TF_VAR_subscription_id'),
                            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
                            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID') ]) {
                                sh 'make plan'
                        }
                    }
                }
            }
        }

        stage('Apply') {
            when {
                environment name: "DESTROY", value: "false"
            }

            steps {
                input 'Start?'
                script {
                    dir('infra/app') {
                        withCredentials([
                            string(credentialsId: 'TF_VAR_admin_password', variable: 'TF_VAR_admin_password'),
                            string(credentialsId: 'TF_VAR_subscription_id', variable: 'TF_VAR_subscription_id'),
                            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
                            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID') ]) {
                                sh 'make apply'
                        }
                    }
                }
            }
        }

        stage('Destroy') {
            when {
                environment name: "DESTROY", value: "true"
            }

            steps {
                input 'Start?'
                script {
                    dir('infra/app') {
                        withCredentials([
                            string(credentialsId: 'TF_VAR_admin_password', variable: 'TF_VAR_admin_password'),
                            string(credentialsId: 'TF_VAR_subscription_id', variable: 'TF_VAR_subscription_id'),
                            string(credentialsId: 'ARM_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                            string(credentialsId: 'ARM_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                            string(credentialsId: 'ARM_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID'),
                            string(credentialsId: 'ARM_TENANT_ID', variable: 'ARM_TENANT_ID') ]) {
                                sh 'make destroy'
                        }
                    }
                }
            }
        }
    }
}
