pipeline {
    agent any

    parameters {
        booleanParam(name: "CREATE_INFRA", defaultValue: true)
    }

    stages {
        stage('Build') {
            parallel {
                stage('Build Employees') {
                    steps {
                        script {
                            dir('source/employees') {
                                sh './gradlew clean build jar'
                            }
                        }
                    }
                }

                stage('Build Payroll') {
                    steps {
                        script {
                            dir('source/payroll') {
                                sh './gradlew clean build jar'
                            }
                        }
                    }
                }
            }
        }

        stage('Test') {
            parallel {
                stage('Test Employees') {
                    steps {
                        script {
                            dir('source/employees') {
                                sh './gradlew test'
                            }
                        }
                    }
                }

                stage('Test Payroll') {
                    steps {
                        script {
                            dir('source/payroll') {
                                sh './gradlew test'
                            }
                        }
                    }
                }
            }
        }

        stage('Deploy Containers') {
            parallel {
                stage('Deploy Employees') {
                    steps {
                        script {
                            dir('source/employees') {
                                sh 'echo build image'
                                sh 'docker build . -t employees'
                                sh 'echo TODO: push image'
                            }
                        }
                    }
                }

                stage('Deploy Payroll') {
                    steps {
                        script {
                            dir('source/payroll') {
                                sh 'echo TODO'
                            }
                        }
                    }
                }
            }
        }

        stage('Create Infra') {
            when {
                environment name: "CREATE_INFRA", value: "true"
            }

            steps {
                input 'Start?'
                build job: 'infra'
            }
        }

        stage('Deploy') {
            steps {
                input 'Start?'
                script {
                    sh 'mkdir -p /var/lib/jenkins/.ssh'
                    sh 'touch /var/lib/jenkins/.ssh/known_hosts'
                    sh 'ssh-keyscan -H dev-watson-app-vm >> /var/lib/jenkins/.ssh/known_hosts'
                    sh 'ansible-playbook cicd/playbooks/playbook.yml -i cicd/playbooks/inventory.ini -e "ansible_ssh_password=P4ssword"'
                }
            }
        }
    }
}
