pipeline {
    agent any

    environment {
        TF_CLI_ARGS = '-no-color'
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    dir('infra/app') {
                        sh 'make init'
                    }
                }
            }
        }

        stage('Validate') {
            steps {
                script {
                    dir('infra/app') {
                        sh 'make validate'
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    dir('infra/app') {
                        sh 'make plan'
                    }
                }
            }
        }

        stage('Apply') {
            steps {
                input 'Start stage?'
                script {
                    dir('infra/app') {
                        sh 'make apply'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                input 'Start deploy?'
                script {
                    sh 'mkdir -p /var/lib/jenkins/.ssh'
                    sh 'touch /var/lib/jenkins/.ssh/known_hosts'
                    sh 'ssh-keyscan -H dev-watson-app-vm >> /var/lib/jenkins/.ssh/known_hosts'
                    sh 'ansible-playbook cd/playbooks/playbook.yml -i cd/playbooks/inventory.ini -e "ansible_ssh_password=P4ssword"'
                }
            }
        }

        stage('Destroy') {
            steps {
                script {
                    dir('infra/app') {
                        sh 'make destroy'
                    }
                }
            }
        }
    }
}
