pipeline {

    agent any

    stages {
        stage('Validate') {
            steps {
                script {
                    sh 'echo validate stage done'
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    sh 'echo plan stage done'
                }
            }
        }

        stage('Apply') {
            steps {
                input 'Start stage?'
                script {
                    sh 'echo apply stage done'
                }
            }
        }

        stage('Deploy') {
            steps {
                input 'Start deploy?'
                script {
                    sh 'mkdir -p /var/lib/jenkins/.ssh'
                    sh 'touch /var/lib/jenkins/.ssh/known_hosts'
                    sh 'ssh-keyscan -H dev-watson-app-vm >> /var/lib/jenkins/.ssh/known_hosts'
                    sh 'ansible-playbook cd/playbooks/playbook.yml -i cd/playbooks/inventory.ini -e "ansible_ssh_password=P4ssword"'
                }
            }
        }
    }
}
