pipeline {

    agent any

    stages {

        stage('Build') {
            parallel{
                stage('Employees') {
                    steps {
                        script {
                            sh 'echo build employees done'
                        }
                    }
                }

                stage('Payroll') {
                    steps {
                        script {
                            sh 'echo build payroll done'
                        }
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo test stage done'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'echo deploy stage done'
                }
            }
        }

        stage('CD pipeline (manual step)') {
            steps {
                input "Start CD pipeline?"
                build job: 'cd'
            }
        }
    }
}
