pipeline {
    agent any

    stages {
        stage('Build') {
            parallel {
                stage('Employees') {
                    steps {
                        script {
                            dir('source/app1') {
                                sh './gradlew clean build jar'
                            }
                        }
                    }
                }

                stage('Payroll') {
                    steps {
                        script {
                            dir('source/app2') {
                                sh './gradlew clean build jar'
                            }
                        }
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo test stage done'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'echo deploy stage done'
                }
            }
        }

        stage('CD pipeline (manual step)') {
            steps {
                input 'Start CD pipeline?'
                build job: 'cd'
            }
        }
    }
}
