version: "3.9"

services:

  payroll:
    image: devwatsonappsvccr.azurecr.io/payroll:latest
    ports:
      - 8080:4567
    environment:
      - EMPLOYEES_URL_PROTOCOL=http
      - EMPLOYEES_URL_HOST=employees
      - EMPLOYEES_URL_PORT=4567

  employees:
    image: devwatsonappsvccr.azurecr.io/employees:latest
